language: ruby
bundler_args: --without debug doc tooling
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
  - rbx-head
notifications:
  irc: "irc.freenode.org#htty"
script: "CODECLIMATE_REPO_TOKEN=dd42b57e9d787d55598ee177bf9a2e19f92a1df04bddb8afbc3251849ccccc25 bundle exec rake test"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: rbx-head
